theme: jekyll-theme-minimal
title: Lebanese Red Cross, Red Crescent - an initial analysis
description: Data Story about IFRC analysis
show_downloads: True
navigation:
  - title: ifrclebanalysis
    url: analysis
